INSERT INTO INVOICE_ITEMS(ID_INVOICE, ID_ITEM, COD_PROD, VALUE_UNIT, QUANTITY, DISCOUNT)
VALUES (1, 1, 1, 25.00, 10, 5);

INSERT INTO INVOICE_ITEMS(ID_INVOICE, ID_ITEM, COD_PROD, VALUE_UNIT, QUANTITY, DISCOUNT)
VALUES (1, 2, 2, 13.50, 3, NULL);

INSERT INTO INVOICE_ITEMS(ID_INVOICE, ID_ITEM, COD_PROD, VALUE_UNIT, QUANTITY, DISCOUNT)
VALUES (1, 3, 3, 15.00, 2, NULL);

INSERT INTO INVOICE_ITEMS(ID_INVOICE, ID_ITEM, COD_PROD, VALUE_UNIT, QUANTITY, DISCOUNT)
VALUES (1, 4, 4, 10.00, 1, NULL);

INSERT INTO INVOICE_ITEMS(ID_INVOICE, ID_ITEM, COD_PROD, VALUE_UNIT, QUANTITY, DISCOUNT)
VALUES (1, 5, 5, 30.00, 1, NULL);

INSERT INTO INVOICE_ITEMS(ID_INVOICE, ID_ITEM, COD_PROD, VALUE_UNIT, QUANTITY, DISCOUNT)
VALUES (2, 1, 3, 15.00, 4, NULL);

INSERT INTO INVOICE_ITEMS(ID_INVOICE, ID_ITEM, COD_PROD, VALUE_UNIT, QUANTITY, DISCOUNT)
VALUES (2, 2, 4, 10.00, 5, NULL);

INSERT INTO INVOICE_ITEMS(ID_INVOICE, ID_ITEM, COD_PROD, VALUE_UNIT, QUANTITY, DISCOUNT)
VALUES (2, 3, 5, 30.00, 7, 0);

INSERT INTO INVOICE_ITEMS(ID_INVOICE, ID_ITEM, COD_PROD, VALUE_UNIT, QUANTITY, DISCOUNT)
VALUES (3, 1, 1, 25.00, 5, NULL);

INSERT INTO INVOICE_ITEMS(ID_INVOICE, ID_ITEM, COD_PROD, VALUE_UNIT, QUANTITY, DISCOUNT)
VALUES (3, 2, 4, 10.00, 4, NULL);

INSERT INTO INVOICE_ITEMS(ID_INVOICE, ID_ITEM, COD_PROD, VALUE_UNIT, QUANTITY, DISCOUNT)
VALUES (3, 3, 5, 30.00, 5, NULL);

INSERT INTO INVOICE_ITEMS(ID_INVOICE, ID_ITEM, COD_PROD, VALUE_UNIT, QUANTITY, DISCOUNT)
VALUES (3, 4, 2, 13.50, 7, NULL);

INSERT INTO INVOICE_ITEMS(ID_INVOICE, ID_ITEM, COD_PROD, VALUE_UNIT, QUANTITY, DISCOUNT)
VALUES (4, 1, 5, 30.00, 10, 15);

INSERT INTO INVOICE_ITEMS(ID_INVOICE, ID_ITEM, COD_PROD, VALUE_UNIT, QUANTITY, DISCOUNT)
VALUES (4, 2, 4, 10.00, 12, 5);

INSERT INTO INVOICE_ITEMS(ID_INVOICE, ID_ITEM, COD_PROD, VALUE_UNIT, QUANTITY, DISCOUNT)
VALUES (4, 3, 1, 25.00, 13, 5);

INSERT INTO INVOICE_ITEMS(ID_INVOICE, ID_ITEM, COD_PROD, VALUE_UNIT, QUANTITY, DISCOUNT)
VALUES (4, 4, 2, 13.50, 15, 5);

INSERT INTO INVOICE_ITEMS(ID_INVOICE, ID_ITEM, COD_PROD, VALUE_UNIT, QUANTITY, DISCOUNT)
VALUES (5, 1, 3, 15.00, 3, NULL);

INSERT INTO INVOICE_ITEMS(ID_INVOICE, ID_ITEM, COD_PROD, VALUE_UNIT, QUANTITY, DISCOUNT)
VALUES (5, 2, 5, 30.00, 6, NULL);

INSERT INTO INVOICE_ITEMS(ID_INVOICE, ID_ITEM, COD_PROD, VALUE_UNIT, QUANTITY, DISCOUNT)
VALUES (6, 1, 1, 25.00, 22, 15);

INSERT INTO INVOICE_ITEMS(ID_INVOICE, ID_ITEM, COD_PROD, VALUE_UNIT, QUANTITY, DISCOUNT)
VALUES (6, 2, 3, 15.00, 25, 20);

INSERT INTO INVOICE_ITEMS(ID_INVOICE, ID_ITEM, COD_PROD, VALUE_UNIT, QUANTITY, DISCOUNT)
VALUES (7, 1, 1, 25.00, 10, 3);

INSERT INTO INVOICE_ITEMS(ID_INVOICE, ID_ITEM, COD_PROD, VALUE_UNIT, QUANTITY, DISCOUNT)
VALUES (7, 2, 2, 13.50, 10, 4);

INSERT INTO INVOICE_ITEMS(ID_INVOICE, ID_ITEM, COD_PROD, VALUE_UNIT, QUANTITY, DISCOUNT)
VALUES (7, 3, 3, 15.00, 10, 4);

INSERT INTO INVOICE_ITEMS(ID_INVOICE, ID_ITEM, COD_PROD, VALUE_UNIT, QUANTITY, DISCOUNT)
VALUES (7, 4, 5, 30.00, 10, 1);






